## Learning Fundamentals of Pytorch

## Tensors

In [1]:
import torch

In [7]:
scalar = torch.tensor(7)
print(f"Tensor: {scalar}")
print(f"Dimension: {scalar.ndim}")
print(f"items: {scalar.item()}")

Tensor: 7
Dimension: 0
items: 7


In [10]:
vector = torch.tensor([1,4])
print(f"Tensor: {vector}")
print(f"Dimension: {vector.ndim}")
print(f"items: {vector.shape}")

Tensor: tensor([1, 4])
Dimension: 1
items: torch.Size([2])


## Matrix

In [15]:
matrix = torch.tensor([[2,6],[5,9]])
print(f"matrix Tensor: {matrix}")
print(f"dimension: {matrix.ndim}")

matrix Tensor: tensor([[2, 6],
        [5, 9]])
dimension: 2


In [33]:
TENSOR = torch.tensor([[[1,2],[4,7]],
                      [[2,8],[9,2]],
                       [[4,7],[2,1]]])
print(f"matrix2 tenosr: {TENSOR}")
print(f"Dimension: {TENSOR.ndim}")
print(f"1st: {TENSOR[0]}")
print(f"Shape: {TENSOR.shape}")

matrix2 tenosr: tensor([[[1, 2],
         [4, 7]],

        [[2, 8],
         [9, 2]],

        [[4, 7],
         [2, 1]]])
Dimension: 3
1st: tensor([[1, 2],
        [4, 7]])
Shape: torch.Size([3, 2, 2])


Shape explained

TENSOR is a 3D tensor with shape (3, 2, 2):

- Dimension 0 → size 3 → number of matrices (or "batches")
- Dimension 1 → size 2 → number of rows in each matrix
- Dimension 2 → size 2 → number of columns in each matrix


## Random Tensor

In [39]:
rand_tensor = torch.rand(2,4,4)
rand_tensor

tensor([[[0.1349, 0.8418, 0.1338, 0.0051],
         [0.3750, 0.4118, 0.6709, 0.1463],
         [0.9305, 0.2371, 0.6422, 0.4961],
         [0.9096, 0.0857, 0.4665, 0.3925]],

        [[0.1504, 0.9058, 0.7934, 0.0150],
         [0.5132, 0.5433, 0.4450, 0.6841],
         [0.2065, 0.1166, 0.4479, 0.9408],
         [0.8973, 0.6392, 0.2522, 0.7160]]])

In [44]:
## Range
range = torch.range(start=2, end=12)
print(range)

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


/tmp/ipython-input-2784355641.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(start=2, end=12)


In [46]:
## Arange
arange = torch.arange(start=2, end=12, step=2)
print(arange)

tensor([ 2,  4,  6,  8, 10])
