## Learning Fundamentals of Pytorch

## Tensors

In [1]:
import torch

In [2]:
scalar = torch.tensor(7)
print(f"Tensor: {scalar}")
print(f"Dimension: {scalar.ndim}")
print(f"items: {scalar.item()}")

Tensor: 7
Dimension: 0
items: 7


In [3]:
vector = torch.tensor([1,4])
print(f"Tensor: {vector}")
print(f"Dimension: {vector.ndim}")
print(f"items: {vector.shape}")

Tensor: tensor([1, 4])
Dimension: 1
items: torch.Size([2])


## Matrix

In [4]:
matrix = torch.tensor([[2,6],[5,9]])
print(f"matrix Tensor: {matrix}")
print(f"dimension: {matrix.ndim}")

matrix Tensor: tensor([[2, 6],
        [5, 9]])
dimension: 2


In [5]:
TENSOR = torch.tensor([[[1,2],[4,7]],
                      [[2,8],[9,2]],
                       [[4,7],[2,1]]])
print(f"matrix2 tenosr: {TENSOR}")
print(f"Dimension: {TENSOR.ndim}")
print(f"1st: {TENSOR[0]}")
print(f"Shape: {TENSOR.shape}")

matrix2 tenosr: tensor([[[1, 2],
         [4, 7]],

        [[2, 8],
         [9, 2]],

        [[4, 7],
         [2, 1]]])
Dimension: 3
1st: tensor([[1, 2],
        [4, 7]])
Shape: torch.Size([3, 2, 2])


Shape explained

TENSOR is a 3D tensor with shape (3, 2, 2):

- Dimension 0 → size 3 → number of matrices (or "batches")
- Dimension 1 → size 2 → number of rows in each matrix
- Dimension 2 → size 2 → number of columns in each matrix


## Random Tensor

In [71]:
rand_tensor = torch.rand(2,4,4)
rand_tensor

tensor([[[0.7780, 0.2472, 0.9656, 0.2826],
         [0.5182, 0.8701, 0.2519, 0.2752],
         [0.6262, 0.5802, 0.1237, 0.6052],
         [0.6070, 0.9177, 0.0193, 0.0515]],

        [[0.7481, 0.2792, 0.7051, 0.5118],
         [0.2777, 0.5326, 0.6890, 0.1921],
         [0.1063, 0.9423, 0.1907, 0.8607],
         [0.7843, 0.8433, 0.3963, 0.5028]]])

In [7]:
## Range
range = torch.range(start=2, end=12)
print(range)

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


/tmp/ipython-input-2784355641.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(start=2, end=12)


In [8]:
## Arange
arange = torch.arange(start=2, end=12, step=2)
print(arange)

tensor([ 2,  4,  6,  8, 10])


## Errors; you will run into with pytorch, and deep learning
1. data type
2. shape of tensors
3. tensors not on the right

## Tensor Datatypes

In [10]:
float_tensor = torch.tensor([1.0,3.5,7.0],
                            dtype=None,           ## Data types
                            device=None,          # what device tensor is on?
                            requires_grad=False)  # whether or not to track with this tensor operations.
print(float_tensor)
print(f"datatype: {float_tensor.dtype}")
print(f"changes it to float 16: {float_tensor.type(torch.float16)}")

tensor([1.0000, 3.5000, 7.0000])
datatype: torch.float32
changes it to float 16: tensor([1.0000, 3.5000, 7.0000], dtype=torch.float16)


## Tensors Attributes
# Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device -to get device from a tensor, can use `tensor.device`

In [13]:
print(f"Tensor: {rand_tensor}")
print(f"Data Type: {rand_tensor.dtype}")
print(f"Shape: {rand_tensor.shape}")
print(f"Device: {rand_tensor.device}")

Tensor: tensor([[[0.8591, 0.9709, 0.7633, 0.8398],
         [0.3563, 0.1300, 0.7732, 0.6135],
         [0.6342, 0.2401, 0.5712, 0.4237],
         [0.6040, 0.6392, 0.5883, 0.8401]],

        [[0.9654, 0.4499, 0.5617, 0.8582],
         [0.1224, 0.7094, 0.1242, 0.1768],
         [0.8231, 0.0892, 0.9619, 0.4862],
         [0.6177, 0.3367, 0.0065, 0.3191]]])
Data Type: torch.float32
Shape: torch.Size([2, 4, 4])
Device: cpu


## Manipulating Tensors
* Addition `torch.add , +`
* Subtraction `torch.substract , -`
* Multiplication (elemet-wise) `torch.mul , *`
* Division `tenosr.div , /`
* Matrix multiplication `tensor.matmul, @`

In [15]:
rand_tensor

tensor([[[0.8591, 0.9709, 0.7633, 0.8398],
         [0.3563, 0.1300, 0.7732, 0.6135],
         [0.6342, 0.2401, 0.5712, 0.4237],
         [0.6040, 0.6392, 0.5883, 0.8401]],

        [[0.9654, 0.4499, 0.5617, 0.8582],
         [0.1224, 0.7094, 0.1242, 0.1768],
         [0.8231, 0.0892, 0.9619, 0.4862],
         [0.6177, 0.3367, 0.0065, 0.3191]]])

In [18]:
rand_tensor_2 = torch.rand(2,4,4)
rand_tensor_2

tensor([[[0.2112, 0.4213, 0.1876, 0.5020],
         [0.6128, 0.6534, 0.3518, 0.0604],
         [0.2222, 0.0747, 0.7080, 0.7621],
         [0.5904, 0.2322, 0.5889, 0.8677]],

        [[0.8208, 0.5427, 0.6200, 0.6976],
         [0.6117, 0.0499, 0.6211, 0.6344],
         [0.2122, 0.5233, 0.6790, 0.7278],
         [0.4688, 0.2429, 0.7215, 0.5632]]])

In [25]:
## Addition
print(f"Adding value to each tensor: \n{rand_tensor +1}\n\n{rand_tensor_2+20}")
print(f"\nAdding both tensor: \n{rand_tensor + rand_tensor_2}")

Adding value to each tensor: 
tensor([[[1.8591, 1.9709, 1.7633, 1.8398],
         [1.3563, 1.1300, 1.7732, 1.6135],
         [1.6342, 1.2401, 1.5712, 1.4237],
         [1.6040, 1.6392, 1.5883, 1.8401]],

        [[1.9654, 1.4499, 1.5617, 1.8582],
         [1.1224, 1.7094, 1.1242, 1.1768],
         [1.8231, 1.0892, 1.9619, 1.4862],
         [1.6177, 1.3367, 1.0065, 1.3191]]])

tensor([[[20.2112, 20.4213, 20.1876, 20.5020],
         [20.6128, 20.6534, 20.3518, 20.0604],
         [20.2222, 20.0747, 20.7080, 20.7621],
         [20.5904, 20.2322, 20.5889, 20.8677]],

        [[20.8208, 20.5427, 20.6200, 20.6976],
         [20.6117, 20.0499, 20.6211, 20.6344],
         [20.2122, 20.5233, 20.6790, 20.7278],
         [20.4688, 20.2429, 20.7215, 20.5632]]])

Adding both tensor: 
tensor([[[1.0703, 1.3922, 0.9509, 1.3418],
         [0.9691, 0.7835, 1.1250, 0.6739],
         [0.8565, 0.3148, 1.2792, 1.1858],
         [1.1943, 0.8714, 1.1772, 1.7077]],

        [[1.7862, 0.9926, 1.1817, 1.5558],
  

In [27]:
## Substraction
print(f"Substracting value to each tensor: \n{rand_tensor -10}\n\n{rand_tensor_2-20}")
print(f"\nSubstracting tensors from each: \n{rand_tensor - rand_tensor_2}")

Substracting value to each tensor: 
tensor([[[-9.1409, -9.0291, -9.2367, -9.1602],
         [-9.6437, -9.8700, -9.2268, -9.3865],
         [-9.3658, -9.7599, -9.4288, -9.5763],
         [-9.3960, -9.3608, -9.4117, -9.1599]],

        [[-9.0346, -9.5501, -9.4383, -9.1418],
         [-9.8776, -9.2906, -9.8758, -9.8232],
         [-9.1769, -9.9108, -9.0381, -9.5138],
         [-9.3823, -9.6633, -9.9935, -9.6809]]])

tensor([[[-19.7888, -19.5787, -19.8124, -19.4980],
         [-19.3872, -19.3466, -19.6482, -19.9396],
         [-19.7778, -19.9253, -19.2920, -19.2379],
         [-19.4096, -19.7678, -19.4111, -19.1323]],

        [[-19.1792, -19.4573, -19.3800, -19.3024],
         [-19.3883, -19.9501, -19.3789, -19.3656],
         [-19.7878, -19.4767, -19.3210, -19.2722],
         [-19.5312, -19.7571, -19.2785, -19.4368]]])

Substracting tensors from each: 
tensor([[[ 6.4791e-01,  5.4951e-01,  5.7569e-01,  3.3779e-01],
         [-2.5647e-01, -5.2338e-01,  4.2135e-01,  5.5303e-01],
         [ 

In [40]:
torch.matmul(rand_tensor,rand_tensor_2)

tensor([[[1.4418, 1.2484, 1.5376, 1.8003],
         [0.6890, 0.4353, 1.0212, 1.3082],
         [0.6582, 0.5652, 0.8574, 1.1358],
         [1.1460, 0.9111, 1.2494, 1.5190]],

        [[1.5892, 1.0488, 1.8785, 1.8510],
         [0.6437, 0.2097, 0.7284, 0.7254],
         [1.1623, 1.0726, 1.5696, 1.6047],
         [0.8640, 0.4330, 0.8267, 0.8289]]])

## Matrix Multiplication
* inner must match
* to fix shape issues, manipulate the shape of one of the tensor


In [41]:
torch.matmul(torch.rand(2,3), torch.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [45]:
torch.matmul(torch.rand(2,3), torch.rand(2,3).T) ## T represnets transpose

tensor([[0.1381, 0.1147],
        [0.3126, 0.1751]])

## Tensors aggregation
- min, max, mean, etc

In [46]:
rand_tensor

tensor([[[0.8591, 0.9709, 0.7633, 0.8398],
         [0.3563, 0.1300, 0.7732, 0.6135],
         [0.6342, 0.2401, 0.5712, 0.4237],
         [0.6040, 0.6392, 0.5883, 0.8401]],

        [[0.9654, 0.4499, 0.5617, 0.8582],
         [0.1224, 0.7094, 0.1242, 0.1768],
         [0.8231, 0.0892, 0.9619, 0.4862],
         [0.6177, 0.3367, 0.0065, 0.3191]]])

In [57]:
print(f"min: {torch.min(rand_tensor)}")
print(f"max: {torch.max(rand_tensor)}")
print(f"mean: {torch.mean(rand_tensor)}")
print(f"median: {torch.median(rand_tensor)}")
print(f"Standard Deviation: {torch.std(rand_tensor)}")
print(f"sum: {torch.sum(rand_tensor)}")
print(f"positional argument for min: {torch.argmin(rand_tensor)}")
print(f"positional argument for max: {torch.argmax(rand_tensor)}")

min: 0.006505072116851807
max: 0.9708514213562012
mean: 0.5454747080802917
median: 0.5882925987243652
Standard Deviation: 0.28686949610710144
sum: 17.455190658569336
positional argument for min: 30
positional argument for max: 1


## Reshaping, view, stacking, squeezing, unsqueezing, permute tensors
* Reshaping - reshape an input to a defined shape
* View - return view of tensors of certain shape but keep the memory as the original tensor
* Stacking - combine multiple tesnors on each other vertical stack(vstack) or side by side(hstack)
* Squeezing - removes all `1` dimension from a tensor
* Unsqueezing - add a `1` dimension to a target tensor
* Permute - Returns a view with dimensions permuted(swaped) in a certain way

In [72]:
rand_tensor, rand_tensor.shape

(tensor([[[0.7780, 0.2472, 0.9656, 0.2826],
          [0.5182, 0.8701, 0.2519, 0.2752],
          [0.6262, 0.5802, 0.1237, 0.6052],
          [0.6070, 0.9177, 0.0193, 0.0515]],
 
         [[0.7481, 0.2792, 0.7051, 0.5118],
          [0.2777, 0.5326, 0.6890, 0.1921],
          [0.1063, 0.9423, 0.1907, 0.8607],
          [0.7843, 0.8433, 0.3963, 0.5028]]]),
 torch.Size([2, 4, 4]))

In [73]:
## reshape
rand_tensor.reshape(4,1,8)

tensor([[[0.7780, 0.2472, 0.9656, 0.2826, 0.5182, 0.8701, 0.2519, 0.2752]],

        [[0.6262, 0.5802, 0.1237, 0.6052, 0.6070, 0.9177, 0.0193, 0.0515]],

        [[0.7481, 0.2792, 0.7051, 0.5118, 0.2777, 0.5326, 0.6890, 0.1921]],

        [[0.1063, 0.9423, 0.1907, 0.8607, 0.7843, 0.8433, 0.3963, 0.5028]]])

In [74]:
## view
x = rand_tensor
x, rand_tensor

(tensor([[[0.7780, 0.2472, 0.9656, 0.2826],
          [0.5182, 0.8701, 0.2519, 0.2752],
          [0.6262, 0.5802, 0.1237, 0.6052],
          [0.6070, 0.9177, 0.0193, 0.0515]],
 
         [[0.7481, 0.2792, 0.7051, 0.5118],
          [0.2777, 0.5326, 0.6890, 0.1921],
          [0.1063, 0.9423, 0.1907, 0.8607],
          [0.7843, 0.8433, 0.3963, 0.5028]]]),
 tensor([[[0.7780, 0.2472, 0.9656, 0.2826],
          [0.5182, 0.8701, 0.2519, 0.2752],
          [0.6262, 0.5802, 0.1237, 0.6052],
          [0.6070, 0.9177, 0.0193, 0.0515]],
 
         [[0.7481, 0.2792, 0.7051, 0.5118],
          [0.2777, 0.5326, 0.6890, 0.1921],
          [0.1063, 0.9423, 0.1907, 0.8607],
          [0.7843, 0.8433, 0.3963, 0.5028]]]))

In [76]:
## changing view will change the original because both shares same memory
x[:,0] = .1111
x, rand_tensor

(tensor([[[0.1111, 0.1111, 0.1111, 0.1111],
          [0.5182, 0.8701, 0.2519, 0.2752],
          [0.6262, 0.5802, 0.1237, 0.6052],
          [0.6070, 0.9177, 0.0193, 0.0515]],
 
         [[0.1111, 0.1111, 0.1111, 0.1111],
          [0.2777, 0.5326, 0.6890, 0.1921],
          [0.1063, 0.9423, 0.1907, 0.8607],
          [0.7843, 0.8433, 0.3963, 0.5028]]]),
 tensor([[[0.1111, 0.1111, 0.1111, 0.1111],
          [0.5182, 0.8701, 0.2519, 0.2752],
          [0.6262, 0.5802, 0.1237, 0.6052],
          [0.6070, 0.9177, 0.0193, 0.0515]],
 
         [[0.1111, 0.1111, 0.1111, 0.1111],
          [0.2777, 0.5326, 0.6890, 0.1921],
          [0.1063, 0.9423, 0.1907, 0.8607],
          [0.7843, 0.8433, 0.3963, 0.5028]]]))

In [90]:
## Stack
print(f"Horizontal stack: \n {torch.hstack([rand_tensor, rand_tensor])}")
print(f"stack: \n {torch.stack([rand_tensor, rand_tensor], dim=0)}")

print(f"Vertical stack: \n {torch.vstack([rand_tensor, rand_tensor])}")
print(f"stack: \n {torch.stack([rand_tensor, rand_tensor], dim=1)}")

Horizontal stack: 
 tensor([[[0.1111, 0.1111, 0.1111, 0.1111],
         [0.5182, 0.8701, 0.2519, 0.2752],
         [0.6262, 0.5802, 0.1237, 0.6052],
         [0.6070, 0.9177, 0.0193, 0.0515],
         [0.1111, 0.1111, 0.1111, 0.1111],
         [0.5182, 0.8701, 0.2519, 0.2752],
         [0.6262, 0.5802, 0.1237, 0.6052],
         [0.6070, 0.9177, 0.0193, 0.0515]],

        [[0.1111, 0.1111, 0.1111, 0.1111],
         [0.2777, 0.5326, 0.6890, 0.1921],
         [0.1063, 0.9423, 0.1907, 0.8607],
         [0.7843, 0.8433, 0.3963, 0.5028],
         [0.1111, 0.1111, 0.1111, 0.1111],
         [0.2777, 0.5326, 0.6890, 0.1921],
         [0.1063, 0.9423, 0.1907, 0.8607],
         [0.7843, 0.8433, 0.3963, 0.5028]]])
stack: 
 tensor([[[[0.1111, 0.1111, 0.1111, 0.1111],
          [0.5182, 0.8701, 0.2519, 0.2752],
          [0.6262, 0.5802, 0.1237, 0.6052],
          [0.6070, 0.9177, 0.0193, 0.0515]],

         [[0.1111, 0.1111, 0.1111, 0.1111],
          [0.2777, 0.5326, 0.6890, 0.1921],
          [0.

In [101]:
x = torch.arange(1, 10, 2).reshape(1,5)
x

tensor([[1, 3, 5, 7, 9]])

In [102]:
## Squeeze
print(f"Before squeeze: \n{x}\n{x.shape}")
print(f"After squeeze: \n{x.squeeze()}\n{x.squeeze().shape}")

Before squeeze: 
tensor([[1, 3, 5, 7, 9]])
torch.Size([1, 5])
After squeeze: 
tensor([1, 3, 5, 7, 9])
torch.Size([5])


In [109]:
## Unsqueeze
print(f"Before unsqueeze: \n{x.squeeze()}\n{x.squeeze().shape}")
print(f"\nAfter unsqueeze: \n{x.squeeze().unsqueeze(dim=0)}\n{x.squeeze().unsqueeze(dim=0).shape}")
print(f"\nAfter unsqueeze: \n{x.squeeze().unsqueeze(dim=1)}\n{x.squeeze().unsqueeze(dim=1).shape}")

Before unsqueeze: 
tensor([1, 3, 5, 7, 9])
torch.Size([5])

After unsqueeze: 
tensor([[1, 3, 5, 7, 9]])
torch.Size([1, 5])

After unsqueeze: 
tensor([[1],
        [3],
        [5],
        [7],
        [9]])
torch.Size([5, 1])


In [120]:
## pemute -- rearrange the dimension of target tensor
x1 = torch.rand(size=(224, 224, 3)) ## height, width, color channels
print(x1.shape)
x_permute  = x1.permute(2, 1, 0) ## color channel, height, width
print(x_permute.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## indexing

In [123]:
rand_tensor

tensor([[[0.1111, 0.1111, 0.1111, 0.1111],
         [0.5182, 0.8701, 0.2519, 0.2752],
         [0.6262, 0.5802, 0.1237, 0.6052],
         [0.6070, 0.9177, 0.0193, 0.0515]],

        [[0.1111, 0.1111, 0.1111, 0.1111],
         [0.2777, 0.5326, 0.6890, 0.1921],
         [0.1063, 0.9423, 0.1907, 0.8607],
         [0.7843, 0.8433, 0.3963, 0.5028]]])

In [124]:
rand_tensor[0]

tensor([[0.1111, 0.1111, 0.1111, 0.1111],
        [0.5182, 0.8701, 0.2519, 0.2752],
        [0.6262, 0.5802, 0.1237, 0.6052],
        [0.6070, 0.9177, 0.0193, 0.0515]])

In [137]:
rand_tensor[:1,:1,:1]

tensor([[[0.1111]]])

In [139]:
rand_tensor[:1,3:,:1]

tensor([[[0.6070]]])